- name: Test folder
  hosts: all
  become: true

  tasks:
  - name: Create folder 
    file:
      path: "{{ dst_dir }}"
      state: directory
      recurse: yes
      owner: "{{ user }}"
      group: "{{ user }}" 
      mode: "0755"